name: Project-Crypto

on:
  push:
    branches: [ master ]
  # pull_request:
    # branches: [ master ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Setup docker buildx 
        uses: docker/setup-buildx-action@v1
        
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOC_USR }}
          password: ${{ secrets.DOC_PWD }}
         
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 
            chsasidhar/project-crypto:latest
            chsasidhar/project-crypto:1.0.1
